{
 "title": "Dashboard 1",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Reads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"} [5m])",
     "legendFormat": "Read operations"
    }
   ]
  },
  {
   "title": "Refused connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_access_denied_errors"
    }
   ]
  },
  {
   "title": "Scrape time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{instance=\"exporter:9104\", job=\"mysql\"}",
     "legendFormat": "Scrape time"
    }
   ]
  }
 ]
}