{
 "title": "Dashboard2",
 "time": { "from": "2019-10-20T23:00:03.500Z", "to": "2019-10-28T23:00:02.500Z" },
 "panels": [
  {
   "title": "Account created",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  id\nFROM sylius_customer\nWHERE\n  $__timeFilter(created_at)\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "Customers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  id\nFROM sylius_customer\nWHERE\n  $__timeFilter(created_at)\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "Total order amouts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  sum(amount) AS \"amount\"\nFROM sylius_payment\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    }
   ]
  },
  {
   "title": "Payments last week",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  id\nFROM sylius_payment\nWHERE\n  $__timeFilter(created_at)\nORDER BY created_at"
    }
   ]
  }
 ]
}