version: '3.7'

services:
    db:
        image: mariadb
        container_name: mysql-database
        restart: on-failure
        environment:
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            - ./scripts:/docker-entrypoint-initdb.d
        networks:
            - bdd
        ports:
            - "3306:3306"
        expose:
            - 3306


    exporter:
        image: prom/mysqld-exporter
        container_name: mysql-exporter
        environment:
            - DATA_SOURCE_NAME=exporter:password@(db:3306)/
        ports:
            - "9104:9104"
        expose:
            - 9104
        networks:
            - bdd
        depends_on:
            - db

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - "9090:9090"
        expose:
            - 9090
        networks:
            - bdd
        volumes:
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        depends_on:
            - exporter

    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: on-failure
        volumes:
            - ./provisioning:/etc/grafana/provisioning
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP="false"
        ports:
            - "3000:3000"
        networks:
            - bdd
        depends_on:
            - prometheus
            - db


networks:
  bdd:
