
global:
    scrape_interval:     15s
    evaluation_interval: 15s

alerting:
    alertmanagers:
    - scheme: http
      timeout: 10s
      static_configs:
        - targets:

scrape_configs:
    - job_name: 'prometheus'
  
      static_configs:
        - targets: ['localhost:9090']

    - job_name: 'mysql'
      static_configs:
        - targets: ['exporter:9104']
